/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as MealPlansRouteImport } from './routes/meal-plans'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MealPlansIndexRouteImport } from './routes/meal-plans.index'
import { Route as MealPlansIdRouteImport } from './routes/meal-plans.$id'

const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlansRoute = MealPlansRouteImport.update({
  id: '/meal-plans',
  path: '/meal-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlansIndexRoute = MealPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MealPlansRoute,
} as any)
const MealPlansIdRoute = MealPlansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MealPlansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meal-plans': typeof MealPlansRouteWithChildren
  '/recipes': typeof RecipesRoute
  '/shopping-list': typeof ShoppingListRoute
  '/meal-plans/$id': typeof MealPlansIdRoute
  '/meal-plans/': typeof MealPlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes': typeof RecipesRoute
  '/shopping-list': typeof ShoppingListRoute
  '/meal-plans/$id': typeof MealPlansIdRoute
  '/meal-plans': typeof MealPlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meal-plans': typeof MealPlansRouteWithChildren
  '/recipes': typeof RecipesRoute
  '/shopping-list': typeof ShoppingListRoute
  '/meal-plans/$id': typeof MealPlansIdRoute
  '/meal-plans/': typeof MealPlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/meal-plans'
    | '/recipes'
    | '/shopping-list'
    | '/meal-plans/$id'
    | '/meal-plans/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recipes' | '/shopping-list' | '/meal-plans/$id' | '/meal-plans'
  id:
    | '__root__'
    | '/'
    | '/meal-plans'
    | '/recipes'
    | '/shopping-list'
    | '/meal-plans/$id'
    | '/meal-plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MealPlansRoute: typeof MealPlansRouteWithChildren
  RecipesRoute: typeof RecipesRoute
  ShoppingListRoute: typeof ShoppingListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plans': {
      id: '/meal-plans'
      path: '/meal-plans'
      fullPath: '/meal-plans'
      preLoaderRoute: typeof MealPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plans/': {
      id: '/meal-plans/'
      path: '/'
      fullPath: '/meal-plans/'
      preLoaderRoute: typeof MealPlansIndexRouteImport
      parentRoute: typeof MealPlansRoute
    }
    '/meal-plans/$id': {
      id: '/meal-plans/$id'
      path: '/$id'
      fullPath: '/meal-plans/$id'
      preLoaderRoute: typeof MealPlansIdRouteImport
      parentRoute: typeof MealPlansRoute
    }
  }
}

interface MealPlansRouteChildren {
  MealPlansIdRoute: typeof MealPlansIdRoute
  MealPlansIndexRoute: typeof MealPlansIndexRoute
}

const MealPlansRouteChildren: MealPlansRouteChildren = {
  MealPlansIdRoute: MealPlansIdRoute,
  MealPlansIndexRoute: MealPlansIndexRoute,
}

const MealPlansRouteWithChildren = MealPlansRoute._addFileChildren(
  MealPlansRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MealPlansRoute: MealPlansRouteWithChildren,
  RecipesRoute: RecipesRoute,
  ShoppingListRoute: ShoppingListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
