/**
 * All types are derived from the OpenAPI spec generated by the backend.
 * Run `npm run generate:types` (from frontend/) after changing backend schemas.
 */
import type { paths } from "./generated/api-types.js";

export type Recipe =
  paths["/api/recipes"]["get"]["responses"][200]["content"]["application/json"][number];
export type RecipeIngredient = Recipe["ingredients"][number];
export type SuitableDays = Recipe["suitableDays"];

export type RecipeInput =
  paths["/api/recipes"]["post"]["requestBody"]["content"]["application/json"];

export type Ingredient =
  paths["/api/ingredients"]["get"]["responses"][200]["content"]["application/json"][number];
export type IngredientInput =
  paths["/api/ingredients"]["post"]["requestBody"]["content"]["application/json"];

export type MealPlan =
  paths["/api/meal-plans"]["get"]["responses"][200]["content"]["application/json"][number];
export type MealPlanDay = MealPlan["days"][number];
export type MealPlanDayRecipe = MealPlanDay["recipe"];

export type MealPlanInput =
  paths["/api/meal-plans"]["post"]["requestBody"]["content"]["application/json"];
export type GenerateMealPlanInput =
  paths["/api/meal-plans/generate"]["post"]["requestBody"]["content"]["application/json"];

export type ShoppingListResponse =
  paths["/api/shopping-list"]["get"]["responses"][200]["content"]["application/json"];
export type ShoppingListItem = ShoppingListResponse["items"][number];
export type ShoppingListQuantity = ShoppingListItem["quantities"][number];
